apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: boutique-shop
  labels:
    app.kubernetes.io/name: boutique-shop
    app.kubernetes.io/component: vector-database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
