apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-sa
  namespace: boutique-shop
  labels:
    app.kubernetes.io/name: boutique-shop
---
apiVersion: v1
kind: Secret
metadata:
  name: boutique-sa-token
  namespace: boutique-shop
  annotations:
    kubernetes.io/service-account.name: boutique-sa
type: kubernetes.io/service-account-token
