/**
 * Generate seed_products.sql from fakestoreapi.com + dummyjson.com.
 *
 * Usage:
 *   node scripts/generate_seed_sql.mjs
 *   → writes ./database/seeds/seed_products_generated.sql
 *
 * Then run on Neon:
 *   psql "$DATABASE_URL" -f database/seeds/seed_products_generated.sql
 *   OR paste into Neon SQL Editor (https://console.neon.tech)
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../database/seeds/seed_products_generated.sql')

const CATEGORIES = [
  ['Electronics',       'Phones, laptops, gadgets and accessories'],
  ['Fashion',           'Clothing, shoes and accessories for men and women'],
  ['Home & Kitchen',    'Furniture, decor, appliances and kitchen essentials'],
  ['Books',             'Books, novels, educational and reference'],
  ['Toys & Games',      'Toys, board games and entertainment for all ages'],
  ['Sports & Outdoors', 'Sports equipment, outdoor gear and fitness'],
  ['Beauty',            'Skincare, makeup, fragrances and personal care'],
]

const CATEGORY_MAP = {
  electronics: 'Electronics', smartphones: 'Electronics', laptops: 'Electronics',
  tablets: 'Electronics', 'mobile-accessories': 'Electronics',
  jewelery: 'Fashion', "men's clothing": 'Fashion', "women's clothing": 'Fashion',
  tops: 'Fashion', 'womens-dresses': 'Fashion', 'womens-shoes': 'Fashion',
  'mens-shirts': 'Fashion', 'mens-shoes': 'Fashion', 'mens-watches': 'Fashion',
  'womens-watches': 'Fashion', 'womens-bags': 'Fashion',
  'womens-jewellery': 'Fashion', sunglasses: 'Fashion',
  fragrances: 'Beauty', skincare: 'Beauty', beauty: 'Beauty',
  groceries: 'Home & Kitchen', 'home-decoration': 'Home & Kitchen',
  furniture: 'Home & Kitchen', 'kitchen-accessories': 'Home & Kitchen',
  lighting: 'Home & Kitchen',
  automotive: 'Sports & Outdoors', motorcycle: 'Sports & Outdoors',
  'sports-accessories': 'Sports & Outdoors',
}

// Escape single quotes for SQL string literals
const sql = (s) => "'" + String(s ?? '').replace(/'/g, "''") + "'"
const truncate = (s, n) => (s ?? '').toString().slice(0, n)

async function fetchFakestore() {
  console.log('→ Fetching fakestoreapi.com (20 products)...')
  const r = await fetch('https://fakestoreapi.com/products')
  if (!r.ok) throw new Error(`fakestoreapi: ${r.status}`)
  const data = await r.json()
  return data.map((p) => ({
    name: truncate(p.title, 255),
    description: p.description || '',
    price: Number(p.price),
    category_raw: (p.category || '').toLowerCase().trim(),
    image_url: truncate(p.image || '', 500),
    stock_quantity: 50,
    featured: (p.rating?.rate ?? 0) >= 4.0,
  }))
}

async function fetchDummyJson(limit = 40) {
  console.log(`→ Fetching dummyjson.com (${limit} products)...`)
  const r = await fetch(`https://dummyjson.com/products?limit=${limit}`)
  if (!r.ok) throw new Error(`dummyjson: ${r.status}`)
  const data = await r.json()
  return (data.products || []).map((p) => ({
    name: truncate(p.title, 255),
    description: p.description || '',
    price: Number(p.price),
    category_raw: (p.category || '').toLowerCase().trim(),
    image_url: truncate(p.thumbnail || (p.images || [])[0] || '', 500),
    stock_quantity: Number.isFinite(p.stock) ? p.stock : 50,
    featured: Number(p.rating ?? 0) >= 4.5,
  }))
}

function buildSql(products) {
  const lines = []
  lines.push('-- Auto-generated by scripts/generate_seed_sql.mjs')
  lines.push('-- Fatima Zehra Amazon Shop — 50+ product seed')
  lines.push(`-- Generated: ${new Date().toISOString()}`)
  lines.push('')
  lines.push('BEGIN;')
  lines.push('')

  // Categories — UPSERT
  lines.push('-- Categories (UPSERT)')
  for (const [name, desc] of CATEGORIES) {
    lines.push(
      `INSERT INTO categories (name, description) VALUES (${sql(name)}, ${sql(desc)})\n` +
        `  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;`
    )
  }
  lines.push('')

  // Wipe products
  lines.push('-- Reset products table')
  lines.push('TRUNCATE products RESTART IDENTITY CASCADE;')
  lines.push('')

  // Products
  lines.push('-- Products')
  const skipped = new Set()
  for (const p of products) {
    const targetCat = CATEGORY_MAP[p.category_raw]
    if (!targetCat) skipped.add(p.category_raw)
    const cat = targetCat || 'Electronics'
    lines.push(
      `INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (\n` +
        `  ${sql(p.name)},\n` +
        `  ${sql(p.description)},\n` +
        `  ${p.price.toFixed(2)},\n` +
        `  (SELECT id FROM categories WHERE name = ${sql(cat)}),\n` +
        `  ${sql(p.image_url)},\n` +
        `  ${p.stock_quantity},\n` +
        `  TRUE,\n` +
        `  ${p.featured ? 'TRUE' : 'FALSE'}\n` +
        `);`
    )
  }
  lines.push('')
  lines.push('COMMIT;')
  lines.push('')
  lines.push('-- Verification:')
  lines.push('-- SELECT c.name, COUNT(p.id) FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.name ORDER BY c.name;')
  lines.push('')

  return { sql: lines.join('\n'), skipped }
}

// Manual products for categories the source APIs don't cover
const MANUAL_PRODUCTS = [
  // Books (6)
  { name: 'The Pragmatic Programmer', description: 'Classic software engineering guide by Hunt & Thomas', price: 1850, category_raw: '__books', image_url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600', stock_quantity: 40, featured: true },
  { name: 'Atomic Habits', description: 'James Clear — tiny changes, remarkable results', price: 1450, category_raw: '__books', image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600', stock_quantity: 80, featured: true },
  { name: 'Clean Code', description: 'Robert C. Martin — handbook of agile software craftsmanship', price: 2100, category_raw: '__books', image_url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600', stock_quantity: 35, featured: false },
  { name: 'Sapiens: A Brief History of Humankind', description: 'Yuval Noah Harari', price: 1750, category_raw: '__books', image_url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600', stock_quantity: 60, featured: true },
  { name: 'Designing Data-Intensive Applications', description: 'Martin Kleppmann — modern data systems', price: 2800, category_raw: '__books', image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600', stock_quantity: 25, featured: false },
  { name: 'The Lean Startup', description: 'Eric Ries — continuous innovation for radically successful businesses', price: 1550, category_raw: '__books', image_url: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=600', stock_quantity: 50, featured: false },

  // Toys & Games (6)
  { name: 'Monopoly Classic Board Game', description: 'Family fun board game', price: 2500, category_raw: '__toys', image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600', stock_quantity: 30, featured: true },
  { name: 'LEGO Classic Creative Bricks', description: '500-piece set for endless creativity', price: 3500, category_raw: '__toys', image_url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600', stock_quantity: 45, featured: true },
  { name: 'Rubiks Cube 3x3', description: 'Original Rubiks puzzle cube', price: 800, category_raw: '__toys', image_url: 'https://images.unsplash.com/photo-1577374903853-3a6c25a64716?w=600', stock_quantity: 100, featured: false },
  { name: 'Remote Control Race Car', description: 'High-speed RC car with rechargeable battery', price: 4500, category_raw: '__toys', image_url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600', stock_quantity: 20, featured: true },
  { name: 'UNO Card Game', description: 'Classic family card game', price: 600, category_raw: '__toys', image_url: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=600', stock_quantity: 120, featured: false },
  { name: 'Stuffed Teddy Bear (Large)', description: 'Soft plush teddy bear, 60cm', price: 1800, category_raw: '__toys', image_url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f86?w=600', stock_quantity: 55, featured: false },

  // Sports & Outdoors (6)
  { name: 'Yoga Mat (6mm Premium)', description: 'Non-slip exercise yoga mat', price: 1500, category_raw: '__sports', image_url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600', stock_quantity: 70, featured: true },
  { name: 'Adjustable Dumbbell Set 20kg', description: 'Adjustable weight dumbbells for home workout', price: 8500, category_raw: '__sports', image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600', stock_quantity: 25, featured: true },
  { name: 'Cricket Bat (English Willow)', description: 'Professional grade English willow bat', price: 12000, category_raw: '__sports', image_url: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600', stock_quantity: 15, featured: true },
  { name: 'Football (Size 5)', description: 'Match-quality football', price: 2200, category_raw: '__sports', image_url: 'https://images.unsplash.com/photo-1614632537190-23e4146777db?w=600', stock_quantity: 60, featured: false },
  { name: 'Camping Tent (4-Person)', description: 'Waterproof family camping tent', price: 9500, category_raw: '__sports', image_url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600', stock_quantity: 18, featured: false },
  { name: 'Cycling Helmet', description: 'Lightweight ventilated cycling helmet', price: 2800, category_raw: '__sports', image_url: 'https://images.unsplash.com/photo-1583500178690-f7fc46f0e4d2?w=600', stock_quantity: 40, featured: false },
]

// Map manual category tags
CATEGORY_MAP['__books'] = 'Books'
CATEGORY_MAP['__toys'] = 'Toys & Games'
CATEGORY_MAP['__sports'] = 'Sports & Outdoors'

;(async () => {
  const all = [...MANUAL_PRODUCTS]
  try { all.push(...(await fetchFakestore())) } catch (e) { console.warn('  ⚠', e.message) }
  try { all.push(...(await fetchDummyJson(40))) } catch (e) { console.warn('  ⚠', e.message) }

  console.log(`→ Total fetched: ${all.length}`)
  if (all.length === 0) { console.error('No products fetched. Check internet.'); process.exit(1) }

  const { sql: out, skipped } = buildSql(all)
  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, out, 'utf8')

  console.log(`✓ Wrote ${all.length} INSERTs → ${OUT}`)
  if (skipped.size) console.log(`  ⚠ Unmapped categories (defaulted to Electronics): ${[...skipped].join(', ')}`)
  console.log('\nNext:')
  console.log(`  psql "$DATABASE_URL" -f ${OUT}`)
  console.log('  OR paste into Neon SQL Editor: https://console.neon.tech')
})()
