-- Auto-generated by scripts/generate_seed_sql.mjs
-- Fatima Zehra Amazon Shop — 50+ product seed
-- Generated: 2026-04-14T02:35:29.171Z

BEGIN;

-- Categories (UPSERT)
INSERT INTO categories (name, description) VALUES ('Electronics', 'Phones, laptops, gadgets and accessories')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Fashion', 'Clothing, shoes and accessories for men and women')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Home & Kitchen', 'Furniture, decor, appliances and kitchen essentials')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Books', 'Books, novels, educational and reference')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Toys & Games', 'Toys, board games and entertainment for all ages')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Sports & Outdoors', 'Sports equipment, outdoor gear and fitness')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;
INSERT INTO categories (name, description) VALUES ('Beauty', 'Skincare, makeup, fragrances and personal care')
  ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

-- Reset products table
TRUNCATE products RESTART IDENTITY CASCADE;

-- Products
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'The Pragmatic Programmer',
  'Classic software engineering guide by Hunt & Thomas',
  1850.00,
  (SELECT id FROM categories WHERE name = 'Books'),
  'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600',
  40,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Atomic Habits',
  'James Clear — tiny changes, remarkable results',
  1450.00,
  (SELECT id FROM categories WHERE name = 'Books'),
  'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600',
  80,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Clean Code',
  'Robert C. Martin — handbook of agile software craftsmanship',
  2100.00,
  (SELECT id FROM categories WHERE name = 'Books'),
  'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600',
  35,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Sapiens: A Brief History of Humankind',
  'Yuval Noah Harari',
  1750.00,
  (SELECT id FROM categories WHERE name = 'Books'),
  'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600',
  60,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Designing Data-Intensive Applications',
  'Martin Kleppmann — modern data systems',
  2800.00,
  (SELECT id FROM categories WHERE name = 'Books'),
  'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600',
  25,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'The Lean Startup',
  'Eric Ries — continuous innovation for radically successful businesses',
  1550.00,
  (SELECT id FROM categories WHERE name = 'Books'),
  'https://images.unsplash.com/photo-1589998059171-988d887df646?w=600',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Monopoly Classic Board Game',
  'Family fun board game',
  2500.00,
  (SELECT id FROM categories WHERE name = 'Toys & Games'),
  'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600',
  30,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'LEGO Classic Creative Bricks',
  '500-piece set for endless creativity',
  3500.00,
  (SELECT id FROM categories WHERE name = 'Toys & Games'),
  'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600',
  45,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Rubiks Cube 3x3',
  'Original Rubiks puzzle cube',
  800.00,
  (SELECT id FROM categories WHERE name = 'Toys & Games'),
  'https://images.unsplash.com/photo-1577374903853-3a6c25a64716?w=600',
  100,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Remote Control Race Car',
  'High-speed RC car with rechargeable battery',
  4500.00,
  (SELECT id FROM categories WHERE name = 'Toys & Games'),
  'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600',
  20,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'UNO Card Game',
  'Classic family card game',
  600.00,
  (SELECT id FROM categories WHERE name = 'Toys & Games'),
  'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=600',
  120,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Stuffed Teddy Bear (Large)',
  'Soft plush teddy bear, 60cm',
  1800.00,
  (SELECT id FROM categories WHERE name = 'Toys & Games'),
  'https://images.unsplash.com/photo-1559454403-b8fb88521f86?w=600',
  55,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Yoga Mat (6mm Premium)',
  'Non-slip exercise yoga mat',
  1500.00,
  (SELECT id FROM categories WHERE name = 'Sports & Outdoors'),
  'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600',
  70,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Adjustable Dumbbell Set 20kg',
  'Adjustable weight dumbbells for home workout',
  8500.00,
  (SELECT id FROM categories WHERE name = 'Sports & Outdoors'),
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
  25,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Cricket Bat (English Willow)',
  'Professional grade English willow bat',
  12000.00,
  (SELECT id FROM categories WHERE name = 'Sports & Outdoors'),
  'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600',
  15,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Football (Size 5)',
  'Match-quality football',
  2200.00,
  (SELECT id FROM categories WHERE name = 'Sports & Outdoors'),
  'https://images.unsplash.com/photo-1614632537190-23e4146777db?w=600',
  60,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Camping Tent (4-Person)',
  'Waterproof family camping tent',
  9500.00,
  (SELECT id FROM categories WHERE name = 'Sports & Outdoors'),
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600',
  18,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Cycling Helmet',
  'Lightweight ventilated cycling helmet',
  2800.00,
  (SELECT id FROM categories WHERE name = 'Sports & Outdoors'),
  'https://images.unsplash.com/photo-1583500178690-f7fc46f0e4d2?w=600',
  40,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
  'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
  109.95,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Mens Casual Premium Slim Fit T-Shirts ',
  'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
  22.30,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Mens Cotton Jacket',
  'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
  55.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Mens Casual Slim Fit',
  'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
  15.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet',
  'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.',
  695.00,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Solid Gold Petite Micropave ',
  'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
  168.00,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'White Gold Plated Princess',
  'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...',
  9.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Pierced Owl Rose Gold Plated Stainless Steel Double',
  'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
  10.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'WD 2TB Elements Portable External Hard Drive - USB 3.0 ',
  'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
  64.00,
  (SELECT id FROM categories WHERE name = 'Electronics'),
  'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
  'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)',
  109.00,
  (SELECT id FROM categories WHERE name = 'Electronics'),
  'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
  '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.',
  109.00,
  (SELECT id FROM categories WHERE name = 'Electronics'),
  'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
  'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty',
  114.00,
  (SELECT id FROM categories WHERE name = 'Electronics'),
  'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
  '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz',
  599.00,
  (SELECT id FROM categories WHERE name = 'Electronics'),
  'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ',
  '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag',
  999.99,
  (SELECT id FROM categories WHERE name = 'Electronics'),
  'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats',
  'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
  56.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Lock and Love Women''s Removable Hooded Faux Leather Moto Biker Jacket',
  '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
  29.95,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
  'Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn''t overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.',
  39.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'MBJ Women''s Solid Short Sleeve Boat Neck V ',
  '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
  9.85,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Opna Women''s Short Sleeve Moisture',
  '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort',
  7.95,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png',
  50,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'DANVOUY Womens T Shirt Casual Cotton Short',
  '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
  12.99,
  (SELECT id FROM categories WHERE name = 'Fashion'),
  'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Essence Mascara Lash Princess',
  'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  9.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp',
  99,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Eyeshadow Palette with Mirror',
  'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.',
  19.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp',
  34,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Powder Canister',
  'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  14.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp',
  89,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Red Lipstick',
  'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  12.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp',
  91,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Red Nail Polish',
  'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
  8.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp',
  79,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Calvin Klein CK One',
  'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.',
  49.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp',
  29,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Chanel Coco Noir Eau De',
  'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
  129.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp',
  58,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Dior J''adore',
  'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.',
  89.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/thumbnail.webp',
  98,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Dolce Shine Eau de',
  'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.',
  69.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp',
  4,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Gucci Bloom Eau de',
  'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.',
  79.99,
  (SELECT id FROM categories WHERE name = 'Beauty'),
  'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp',
  91,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Annibale Colombo Bed',
  'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
  1899.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp',
  88,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Annibale Colombo Sofa',
  'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
  2499.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp',
  60,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Bedside Table African Cherry',
  'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.',
  299.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp',
  64,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Knoll Saarinen Executive Conference Chair',
  'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
  499.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp',
  26,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Wooden Bathroom Sink With Mirror',
  'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.',
  799.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp',
  7,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Apple',
  'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.',
  1.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp',
  8,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Beef Steak',
  'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.',
  12.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp',
  86,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Cat Food',
  'Nutritious cat food formulated to meet the dietary needs of your feline friend.',
  8.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp',
  46,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Chicken Meat',
  'Fresh and tender chicken meat, suitable for various culinary preparations.',
  9.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp',
  97,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Cooking Oil',
  'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.',
  4.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp',
  10,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Cucumber',
  'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.',
  1.49,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp',
  84,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Dog Food',
  'Specially formulated dog food designed to provide essential nutrients for your canine companion.',
  10.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp',
  71,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Eggs',
  'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.',
  2.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp',
  9,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Fish Steak',
  'Quality fish steak, suitable for grilling, baking, or pan-searing.',
  14.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp',
  74,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Green Bell Pepper',
  'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.',
  1.29,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp',
  33,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Green Chili Pepper',
  'Spicy green chili pepper, ideal for adding heat to your favorite recipes.',
  0.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp',
  3,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Honey Jar',
  'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.',
  6.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp',
  34,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Ice Cream',
  'Creamy and delicious ice cream, available in various flavors for a delightful treat.',
  5.49,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp',
  27,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Juice',
  'Refreshing fruit juice, packed with vitamins and great for staying hydrated.',
  3.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp',
  50,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Kiwi',
  'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.',
  2.49,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp',
  99,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Lemon',
  'Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.',
  0.79,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/lemon/thumbnail.webp',
  31,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Milk',
  'Fresh and nutritious milk, a staple for various recipes and daily consumption.',
  3.49,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp',
  27,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Mulberry',
  'Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.',
  4.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/mulberry/thumbnail.webp',
  99,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Nescafe Coffee',
  'Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.',
  7.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp',
  57,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Potatoes',
  'Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.',
  2.29,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp',
  13,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Protein Powder',
  'Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.',
  19.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp',
  80,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Red Onions',
  'Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.',
  1.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/red-onions/thumbnail.webp',
  82,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Rice',
  'High-quality rice, a staple for various cuisines and a versatile base for many dishes.',
  5.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp',
  59,
  TRUE,
  FALSE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Soft Drinks',
  'Assorted soft drinks in various flavors, perfect for refreshing beverages.',
  1.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp',
  53,
  TRUE,
  TRUE
);
INSERT INTO products (name, description, price, category_id, image_url, stock_quantity, is_active, featured) VALUES (
  'Strawberry',
  'Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.',
  3.99,
  (SELECT id FROM categories WHERE name = 'Home & Kitchen'),
  'https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp',
  46,
  TRUE,
  FALSE
);

COMMIT;

-- Verification:
-- SELECT c.name, COUNT(p.id) FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.name ORDER BY c.name;
